#!/bin/bash

localbin="$HOME/.local/bin/"
echo "Installing to $localbin"

mkdir -p ~/.local/bin/

for prog in "p2e-dev-node1" "git-module-rm-all"
do

	if [ -r "${localbin}/${prog}" ]
	then
		echo "${prog} - already installed "
	else
		echo "${prog}- installing"
		ln -s "${PWD}/${prog}" 	"${localbin}/" || echo "Failed to link"
	fi

done
